create table public.membership_type
(
    id         integer generated by default as identity
        constraint membershiptype_pkey
            primary key,
    type       varchar(50),
    gym_visits integer,
    spa_visits integer,
    duration   integer,
    price      numeric(10, 2)
)
    using ???;

alter table public.membership_type
    owner to postgres;

