create table public.person
(
    id         integer generated by default as identity
        primary key,
    username   varchar(30)  not null,
    first_name varchar(20),
    last_name  varchar(20),
    bd_date    date,
    email      varchar(100) not null
        unique,
    role       varchar(100),
    password   varchar(100) not null
)
    using ???;

alter table public.person
    owner to postgres;

