create table public.privilege
(
    id          integer generated by default as identity
        primary key,
    name        varchar(255),
    description text
)
    using ???;

alter table public.privilege
    owner to postgres;

