create table public.spa_procedures
(
    id          integer generated by default as identity
        primary key,
    name        varchar(255) not null,
    description text,
    duration    integer,
    type        varchar(15)
)
    using ???;

alter table public.spa_procedures
    owner to postgres;

