create table public.trainers
(
    id             integer generated by default as identity
        primary key,
    username       varchar(255) not null,
    name           varchar(255) not null,
    password       varchar(100) not null,
    email          varchar(100) not null
        unique,
    specialization varchar(255),
    experience     integer,
    bio            text,
    role           varchar(100)
)
    using ???;

alter table public.trainers
    owner to postgres;

