create table public.workout_booking
(
    id         integer generated by default as identity
        primary key,
    user_id    integer
        references public.person,
    trainer_id integer
        references public.trainers,
    date       timestamp,
    status     varchar(50) default 'Зарегистрирован(а)'::character varying
)
    using ???;

alter table public.workout_booking
    owner to postgres;

